Customisation of abbreviations text size upto 14sp
Applandeo/Material-Calendar-View pull request #375
Opened 2021-03-29 08:52 UTC by SahanaHalodoc

2021-03-29 08:53 UTC, SahanaHalodoc commented
@kormateusz Please review.

2021-03-29 08:58 UTC, kormateusz commented on library/src/main/java/com/applandeo/materialcalendarview/utils/AppearanceUtils.kt
> +internal fun View.setAbbreviationsLabelsSize(size: Float){
Please format this class.

2021-03-29 08:59 UTC, kormateusz requested changes

2021-03-29 08:59 UTC, kormateusz commented on library/src/main/java/com/applandeo/materialcalendarview/utils/AppearanceUtils.kt
> +        if(size>0.0 && size<=28.0) {
Why below 28.0?

2021-03-29 12:11 UTC, SahanaHalodoc commented on library/src/main/java/com/applandeo/materialcalendarview/utils/AppearanceUtils.kt
> +internal fun View.setAbbreviationsLabelsSize(size: Float){
This is done @kormateusz

2021-03-29 12:13 UTC, SahanaHalodoc commented on library/src/main/java/com/applandeo/materialcalendarview/utils/AppearanceUtils.kt
> +        if(size>0.0 && size<=28.0) {
This is resolved in the latest commit.

2021-03-31 09:30 UTC, sahanaprabhakar-halodoc commented
@kormateusz Can you please review and merge

2021-03-31 09:55 UTC, kormateusz approved these changes

2021-03-31 12:17 UTC, sahanaprabhakar-halodoc commented
@kormateusz can this be merged please

2021-04-07 07:18 UTC, sahanaprabhakar-halodoc commented
@kormateusz Any update on when this can be merged?

2021-04-15 05:17 UTC, sahanaprabhakar-halodoc commented
@kormateusz Can we merge this please?

2021-04-15 05:23 UTC, merged